=== motorina0/gone/public/content/schemas/projection.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "minLength": 1
    },
    "schemaVersion": {
      "type": "string",
      "pattern": "^\\d+\\.\\d+\\.\\d+$"
    },
    "name": {
      "type": "string"
    },
    "kind": {
      "enum": [
        "isometric",
        "top"
      ]
    },
    "matrix": {
      "type": "array",
      "items": {
        "type": "number"
      },
      "minItems": 4,
      "maxItems": 4
    },
    "origin": {
      "type": "object",
      "required": [
        "x",
        "y"
      ]
    },
    "scale": {
      "type": "number",
      "exclusiveMinimum": 0
    },
    "azimuth": {
      "type": "number"
    },
    "elevation": {
      "type": "number"
    }
  },
  "required": [
    "id",
    "schemaVersion",
    "kind",
    "matrix",
    "origin",
    "scale",
    "azimuth",
    "elevation"
  ]
}

=== motorina0/gone/public/content/locations/piata-unirii/projections/view-90.json
{
  "schemaVersion": "1.0.0",
  "id": "view-90",
  "name": "90° isometric",
  "kind": "isometric",
  "azimuth": 90,
  "elevation": 35.264,
  "matrix": [
    4.7761225166746774e-17,
    -0.78,
    0.35100000000000003,
    2.1492551325036047e-17
  ],
  "origin": {
    "x": 480,
    "y": 130
  },
  "scale": 7
}

=== motorina0/gone/public/content/locations/vatra-central-station/projections/view-180.json
{
  "schemaVersion": "1.0.0",
  "id": "view-180",
  "name": "180\u00b0 isometric",
  "kind": "isometric",
  "azimuth": 180,
  "elevation": 35.264,
  "matrix": [
    0.8660000000000002,
    -0.8659999999999999,
    -0.49999999999999994,
    -0.5000000000000001
  ],
  "origin": {
    "x": 372.4999999999999,
    "y": 568.2678983833719
  },
  "scale": 1.0344495765973825
}
